name: llm_kristy
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.7.14
  - cudatoolkit=11.8.0
  - git=2.49.0
  - git-lfs=3.7.0
  - keyutils=1.6.1
  - krb5=1.21.3
  - ld_impl_linux-64=2.43
  - libabseil=20250512.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=8.14.1
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.0
  - libffi=3.4.6
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libgomp=15.1.0
  - libiconv=1.18
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libopenblas=0.3.30
  - libsqlite=3.50.2
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - numpy=1.26.4
  - openssl=3.5.1
  - pcre2=10.45
  - perl=5.32.1
  - pip=25.1.1
  - protobuf=6.31.1
  - python=3.9.23
  - python_abi=3.9
  - readline=8.2
  - setuptools=80.9.0
  - tk=8.6.13
  - wheel=0.45.1
  - zstd=1.5.7
  - pip:
      - accelerate==1.9.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.14
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyio==4.9.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - blake3==1.0.5
      - cachetools==6.1.0
      - certifi==2025.7.14
      - charset-normalizer==3.4.2
      - cloudpickle==3.1.1
      - distro==1.9.0
      - dotenv==0.9.9
      - exceptiongroup==1.3.0
      - fastapi==0.116.1
      - filelock==3.18.0
      - flashinfer-python==0.2.5+cu118torch2.6
      - frozenlist==1.7.0
      - fsspec==2025.7.0
      - gguf==0.17.1
      - h11==0.16.0
      - hf-xet==1.1.5
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.33.4
      - idna==3.10
      - importlib-metadata==8.7.0
      - jinja2==3.1.6
      - jiter==0.10.0
      - llguidance==1.0.1
      - llvmlite==0.43.0
      - markupsafe==3.0.2
      - mpmath==1.3.0
      - msgspec==0.19.0
      - multidict==6.6.3
      - networkx==3.2.1
      - numba==0.60.0
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.20.5
      - nvidia-nvtx-cu11==11.8.86
      - openai==1.97.0
      - packaging==25.0
      - pandas==2.3.1
      - pillow==11.3.0
      - prometheus-client==0.22.1
      - propcache==0.3.2
      - psutil==7.0.0
      - py-cpuinfo==9.0.0
      - pybase64==1.4.1
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - pytz==2025.2
      - pyyaml==6.0.2
      - pyzmq==27.0.0
      - regex==2024.11.6
      - requests==2.32.4
      - safetensors==0.5.3
      - six==1.17.0
      - sniffio==1.3.1
      - starlette==0.47.1
      - sympy==1.13.1
      - tokenizers==0.21.2
      - torch==2.6.0+cu118
      - torchaudio==2.6.0+cu118
      - torchvision==0.21.0+cu118
      - tqdm==4.67.1
      - transformers==4.53.2
      - triton==3.0.0
      - typing-extensions==4.14.1
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - vllm==0.8.3+cu118
      - xformers==0.0.27.post2+cu118
      - yarl==1.20.1
      - zipp==3.23.0
      - zmq==0.0.0
prefix: /oak/stanford/groups/rbaltman/gnayar/software/miniconda3/envs/llm_kristy
